line-length = 110
target-version = "py313"

[lint]
select = [
    "B",
    "D",
    "E",
    "F",
    "I",
    "SIM",
    "UP",
    "W"
]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104"
]

[lint.isort]
force-sort-within-sections = true

[lint.pydocstyle]
convention = "numpy"
